support read content from stdin and file

diff --git a/bin/idea b/bin/idea
--- a/bin/idea
+++ b/bin/idea
@@ -6,7 +6,7 @@ usage(){
   echo ""
   echo "COMMANDS"
   echo "  open              create a new note or open the existion note"
-  echo "  git-sync           flush all the notes to git"
+  echo "  git-sync          flush all the notes to git"
   echo "  ls                list all the notes in 3 days"
   echo "  search <pattern>  serach all the notes which match the given pattern"
 }
@@ -24,6 +24,7 @@ colorful_output_files(){
 
 open(){
   local local_directory=$IDEA_LOCAL
+  local append_content=""
   local note=""
 
   while [[ $# -gt 0 ]]
@@ -40,8 +41,33 @@ open(){
         local_directory=$1
         shift
         ;;
+      --file)
+        if [ "$source" != "" ]
+        then
+          echo "--file can't be used together with $source."
+          exit 1
+        fi
+
+        if [ ! -f $1 ]
+        then
+          echo "$1 doesn't exist."
+          exit 1
+        fi
+        source="--file"
+        append_content=$(cat $1)
+        shift
+        ;;
+      --stdin)
+        if [ "$source" != "" ]
+        then
+          echo "--stdin can't be used together with $source."
+          exit 1
+        fi
+        source="--stdin"
+        read append_content
+        ;;
       help)
-        echo "open [--local <value>] [<note name>]"
+        echo "open [--local <value>] [--file <value>|--stdin] [<note name>]"
         echo ""
         echo "DESCRIPTION"
         echo "  1. If the note name is not given, create a new note with random name."
@@ -50,6 +76,8 @@ open(){
         echo ""
         echo "OPTIONS"
         echo "  --local   Specify the local notes directory explicitly, will use environment variable IDEA_LOCAL if missing."
+        echo "  --file    Append the file content to the note"
+        echo "  --stdin   Append the stdin to the note"
         exit 0
         ;;
       *)
@@ -81,7 +109,12 @@ open(){
     fi
   fi
 
-  cd ${local_directory} && $EDITOR "$local_directory/$note"
+  if [[ "$append_content" != "" ]]
+  then
+    cd ${local_directory} && echo $append_content >> $note && $EDITOR $note
+  else
+    cd ${local_directory} && $EDITOR $note
+  fi
 }
 
 
